version: "3" 
services: 
  xmr-xfast-container: 
    command: ['--user', 'jazzqi@gmail.com', '--xmr'] 
    container_name: xmr-xfast-container 
    image: minergate-xfast-cli 
    restart: unless-stopped 
    network_mode: bridge 
